# Generated by Django 6.0.2 on 2026-02-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(help_text='Ruta URL, ej: views/users/', max_length=255, unique=True)),
                ('template_name', models.CharField(help_text='Ruta del template, ej: Users/users.html', max_length=255)),
                ('name', models.CharField(help_text='Nombre único de la ruta, ej: view-users', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si la ruta está habilitada o no')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'view_routes',
                'ordering': ['url_path'],
            },
        ),
    ]
