# Generated by Django 6.0.2 on 2026-02-19 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_viewroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_get', models.BooleanField(default=False, help_text='Permiso para GET (ver la vista)')),
                ('can_post', models.BooleanField(default=False, help_text='Permiso para POST (crear)')),
                ('can_put', models.BooleanField(default=False, help_text='Permiso para PUT (actualizar)')),
                ('can_delete', models.BooleanField(default=False, help_text='Permiso para DELETE (eliminar)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.viewroute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_permissions', to='accounts.user')),
            ],
            options={
                'db_table': 'route_permissions',
                'ordering': ['route__url_path', 'user__username'],
                'unique_together': {('user', 'route')},
            },
        ),
    ]
