# Generated by Django 6.0.2 on 2026-02-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_modules_families_subfamilies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(help_text='ID del usuario que realizó la grabación')),
                ('name', models.CharField(help_text='Nombre descriptivo de la grabación', max_length=255)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duración en segundos', null=True)),
                ('sample_rate', models.IntegerField(default=44100, help_text='Frecuencia de muestreo en Hz')),
                ('audio_data', models.BinaryField(blank=True, help_text='Datos de audio en formato binario', null=True)),
                ('file_type', models.CharField(default='audio/webm', help_text='MIME type del audio', max_length=50)),
                ('file_size', models.IntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recordings',
                'ordering': ['-created_at'],
            },
        ),
    ]
