# Generated by Django 6.0.2 on 2026-02-20 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_recordings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la canción', max_length=255)),
                ('artist', models.CharField(default='Desconocido', help_text='Artista', max_length=255)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duración en segundos', null=True)),
                ('file_type', models.CharField(default='audio/mpeg', help_text='MIME type', max_length=50)),
                ('file_size', models.IntegerField(blank=True, help_text='Tamaño en bytes', null=True)),
                ('audio_data', models.BinaryField(blank=True, help_text='Audio original (binario)', null=True)),
                ('fingerprint_count', models.IntegerField(default=0, help_text='Cantidad de fingerprints generados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'songs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, help_text='SHA-1 hash del pico espectral', max_length=40)),
                ('time_offset', models.IntegerField(help_text='Offset temporal en frames desde el inicio')),
                ('song', models.ForeignKey(help_text='Canción a la que pertenece este fingerprint', on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='accounts.song')),
            ],
            options={
                'db_table': 'fingerprints',
                'indexes': [models.Index(fields=['hash'], name='idx_fingerprint_hash')],
            },
        ),
    ]
